[project]
name = "2026-09-02-actvity-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vikrant Pradhan", email = "pradhan.vikrant@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
2026-09-02-actvity-tracker = "2026_09_02_actvity_tracker:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
